#!/usr/bin/env python3
"""
ELM Setup Plotting
src/core/elm_setup_plotting.py

Setup-time figures showing model configuration.
Generated by ELMExpManager._build() into 02_setup_plots/.

Public functions:
    plot_domain_configuration(experiment, elm_config, output_path)
        Per-experiment: soil column + config info + forcing window.
        Output: 02_setup_plots/exp_NNN_<case_name>/domain_configuration.png

    compare_experiments(experiments, output_path)
        Cross-experiment parameter matrix.
        Output: 02_setup_plots/comparison_experiments.png

    compare_forcing_conditions(experiments, output_path)
        Timeline of forcing windows within Qian 1948–2004.
        Output: 02_setup_plots/comparison_forcing_conditions.png

All three return True on success, False on failure (matplotlib missing,
partial data, etc.). Failures log a warning and do not raise.
"""
import logging
from typing import Dict, List, Any

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────
QIAN_START_YEAR = 1948
QIAN_END_YEAR   = 2004

# ELM nlevsoi=10 layer bottoms (meters) — for grid overlay on soil column
ELM_LEVEL_BOTTOM_M = [
    0.018, 0.045, 0.091, 0.166, 0.289,
    0.493, 0.829, 1.383, 2.296, 3.802,
]

# Period colors used across all three plots
PERIOD_COLORS = {
    'baseline': '#3D7CB0',  # steel blue
    'dry':      '#C0392B',  # red
    'wet':      '#27AE60',  # green
}

# Synthetic-soil texture summaries (used in soil-column labels)
SYNTHETIC_SOIL_LABELS = {
    'sandy':  '#E5C100',
    'loamy':  '#A0826D',
    'clayey': '#8B4513',
}


# ─────────────────────────────────────────────────────────────────────
# UTILITIES
# ─────────────────────────────────────────────────────────────────────
def _import_matplotlib():
    """Lazy-import matplotlib; force non-interactive backend. Returns plt or None."""
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        return plt
    except ImportError as e:
        logger.warning(f"matplotlib not available: {e}")
        return None


def _layer_val(layer: dict, *keys, default=0.0):
    """Try multiple key names (MCP data has variable naming)."""
    for k in keys:
        if k in layer and layer[k] is not None:
            return layer[k]
    return default


# ─────────────────────────────────────────────────────────────────────
# 1. PER-EXPERIMENT DOMAIN FIGURE
# ─────────────────────────────────────────────────────────────────────
def plot_domain_configuration(experiment:  Dict[str, Any],
                              elm_config:  Dict[str, Any],
                              output_path: str) -> bool:
    """Per-experiment setup figure: soil column + config info + forcing window."""
    plt = _import_matplotlib()
    if plt is None:
        return False

    try:
        fig = plt.figure(figsize=(14, 6.5))
        gs  = fig.add_gridspec(
            1, 3, width_ratios=[1, 1.2, 1.4],
            wspace=0.35,
        )

        _draw_soil_column(    fig.add_subplot(gs[0, 0]), experiment, elm_config)
        _draw_config_panel(   fig.add_subplot(gs[0, 1]), experiment, elm_config)
        _draw_forcing_window( fig.add_subplot(gs[0, 2]), experiment)

        case_name = experiment.get('case_name', 'experiment')
        fig.suptitle(f"Domain Configuration — {case_name}",
                     fontsize=14, fontweight='bold', y=0.98)

        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        return True

    except Exception as e:
        logger.warning(f"plot_domain_configuration failed: {e}")
        return False


def _draw_soil_column(ax, exp, elm_config):
    """Vertical soil column showing texture per layer + ELM grid."""
    soil_profile = (elm_config or {}).get('soil_profile') or {}
    layers       = soil_profile.get('layers') or []
    soil_config  = exp.get('soil_config', 'native')
    substrate    = exp.get('substrate', '') or ''

    ax.set_xlim(0, 100)
    ax.set_ylim(3.5, 0)  # depth: 0 at top
    ax.set_xlabel('Texture fraction (%)')
    ax.set_ylabel('Depth (m)')
    ax.set_title('Soil Column', fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.3, axis='x')

    if soil_config == 'native' and layers:
        # Draw SSURGO layers
        ssurgo_bottom = 0.0
        for layer in layers:
            top  = _layer_val(layer, 'depth_top_m', 'top_m', 'top', default=0)
            bot  = _layer_val(layer, 'depth_bot_m', 'bot_m', 'bottom',
                              'depth_bottom_m', default=top + 0.3)
            sand = _layer_val(layer, 'sand_pct', 'sand', default=0)
            clay = _layer_val(layer, 'clay_pct', 'clay', default=0)

            ax.fill_betweenx([top, bot], 0, sand,
                             color='#E5C100', alpha=0.75, edgecolor='white')
            ax.fill_betweenx([top, bot], sand, min(100, sand + clay),
                             color='#8B4513', alpha=0.75, edgecolor='white')
            ssurgo_bottom = max(ssurgo_bottom, bot)

        # Mark substrate region below SSURGO
        if ssurgo_bottom < 3.4:
            ax.axhspan(ssurgo_bottom, 3.4, alpha=0.15, color='gray')
            ax.axhline(ssurgo_bottom, color='red',
                       linestyle='--', linewidth=1.5)
            ax.text(50, ssurgo_bottom - 0.05, 'SSURGO base',
                    fontsize=9, color='red', ha='center', va='bottom')
            ax.text(50, (ssurgo_bottom + 3.4) / 2,
                    f'Substrate:\n{substrate}',
                    fontsize=10, color='#555',
                    ha='center', va='center', style='italic')

        from matplotlib.patches import Patch
        ax.legend(handles=[
            Patch(color='#E5C100', label='Sand', alpha=0.75),
            Patch(color='#8B4513', label='Clay', alpha=0.75),
        ], loc='lower right', fontsize=9, framealpha=0.95)

    else:
        # Uniform synthetic soil
        color = SYNTHETIC_SOIL_LABELS.get(soil_config, '#888888')
        ax.axhspan(0, 3.4, color=color, alpha=0.45)
        ax.text(50, 1.7,
                f'Uniform synthetic\n({soil_config})',
                ha='center', va='center', fontsize=11, fontweight='bold',
                color='#333')

    # ELM grid overlay (dotted lines at each level bottom)
    for d in ELM_LEVEL_BOTTOM_M:
        ax.axhline(d, color='gray', linestyle=':',
                   linewidth=0.5, alpha=0.6)
    ax.text(99, 3.42, 'ELM grid (10 levels)',
            fontsize=8, color='gray',
            ha='right', va='top', style='italic')


def _draw_config_panel(ax, exp, elm_config):
    """Configuration metadata as labeled text rows."""
    ax.axis('off')
    ax.set_title('Configuration', fontsize=12, fontweight='bold')

    elm_config = elm_config or {}
    lat = elm_config.get('lat')
    lon = elm_config.get('lon')

    info = [
        ('Case',      exp.get('case_name', '?')),
        ('Scenario',  exp.get('scenario_name', '?')),
        ('Forcing',   str(exp.get('forcing_period', '?')).capitalize()),
        ('Years',     f"{exp.get('forcing_start', '?')}–"
                      f"{exp.get('forcing_end', '?')}"),
        ('STOP_N',    exp.get('stop_n', '?')),
        ('Latitude',  f"{lat}°" if lat is not None else 'N/A'),
        ('Longitude', f"{lon}°" if lon is not None else 'N/A'),
        ('Soil',      exp.get('soil_config', '?')),
        ('Substrate', exp.get('substrate') or '—'),
    ]

    y = 0.93
    for key, val in info:
        ax.text(0.05, y, f"{key}:",
                fontsize=11, fontweight='bold',
                transform=ax.transAxes, color='#333',
                verticalalignment='top')
        ax.text(0.45, y, str(val),
                fontsize=11,
                transform=ax.transAxes, color='#555',
                verticalalignment='top')
        y -= 0.09


def _draw_forcing_window(ax, exp):
    """Timeline: full Qian range + this experiment's window highlighted."""
    period   = exp.get('forcing_period', 'baseline')
    yr_start = exp.get('forcing_start')
    yr_end   = exp.get('forcing_end')
    color    = PERIOD_COLORS.get(period, 'gray')

    ax.set_xlim(QIAN_START_YEAR - 2, QIAN_END_YEAR + 2)
    ax.set_ylim(0, 1)
    ax.set_yticks([])
    ax.set_xlabel('Year')
    ax.set_title('Forcing Window (Qian DATM_CLMNCEP)',
                 fontsize=12, fontweight='bold')

    # Full Qian range as background bar
    ax.axvspan(QIAN_START_YEAR, QIAN_END_YEAR,
               ymin=0.35, ymax=0.65, color='lightgray', alpha=0.5)
    ax.text(QIAN_START_YEAR, 0.78, f'{QIAN_START_YEAR}',
            fontsize=9, color='#555')
    ax.text(QIAN_END_YEAR, 0.78, f'{QIAN_END_YEAR}',
            fontsize=9, color='#555', ha='right')
    ax.text((QIAN_START_YEAR + QIAN_END_YEAR) / 2, 0.5,
            'Full Qian range', fontsize=9, color='#555',
            ha='center', alpha=0.6)

    # This experiment's window
    if yr_start is not None and yr_end is not None:
        ax.axvspan(yr_start, yr_end + 1, ymin=0.20, ymax=0.80,
                   color=color, alpha=0.85)
        ax.text((yr_start + yr_end + 1) / 2, 0.12,
                f'{yr_start}–{yr_end}\n({period})',
                fontsize=10, ha='center', va='top',
                color=color, fontweight='bold')

    ax.grid(True, axis='x', alpha=0.3)


# ─────────────────────────────────────────────────────────────────────
# 2. CROSS-EXPERIMENT COMPARISON TABLE
# ─────────────────────────────────────────────────────────────────────
def compare_experiments(experiments: List[Dict[str, Any]],
                        output_path: str) -> bool:
    """Cross-experiment parameter matrix as a styled table."""
    plt = _import_matplotlib()
    if plt is None or not experiments:
        return False

    try:
        n = len(experiments)
        fig, ax = plt.subplots(figsize=(max(8, 2.5 * n), 4.5))
        ax.axis('off')
        ax.set_title('Experiment Comparison',
                     fontsize=14, fontweight='bold', pad=20)

        rows = [
            ('Forcing Period',
             [str(e.get('forcing_period', '—')).capitalize()
              for e in experiments]),
            ('Year Range',
             [f"{e.get('forcing_start', '?')}–{e.get('forcing_end', '?')}"
              for e in experiments]),
            ('STOP_N',
             [str(e.get('stop_n', '?')) for e in experiments]),
            ('Soil Config',
             [str(e.get('soil_config', '—')) for e in experiments]),
            ('Substrate',
             [str(e.get('substrate') or '—') for e in experiments]),
        ]
        col_labels = [e.get('case_name', f'exp_{i:03d}')
                      for i, e in enumerate(experiments)]
        row_labels = [r[0] for r in rows]
        cell_text  = [r[1] for r in rows]

        table = ax.table(
            cellText  = cell_text,
            rowLabels = row_labels,
            colLabels = col_labels,
            cellLoc   = 'center',
            loc       = 'center',
            colLoc    = 'center',
        )
        table.auto_set_font_size(False)
        table.set_fontsize(10)
        table.scale(1, 1.7)

        # Style header row
        for j in range(n):
            cell = table[0, j]
            cell.set_facecolor('#3D7CB0')
            cell.set_text_props(color='white', weight='bold')

        # Style row-label column
        for i in range(1, len(row_labels) + 1):
            cell = table[i, -1]
            cell.set_facecolor('#E8EEF4')
            cell.set_text_props(weight='bold')

        # Color-code Forcing Period row by period
        for j, exp in enumerate(experiments):
            period = exp.get('forcing_period', '')
            if period in PERIOD_COLORS:
                cell = table[1, j]
                cell.set_facecolor(PERIOD_COLORS[period])
                cell.set_text_props(color='white', weight='bold')

        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        return True

    except Exception as e:
        logger.warning(f"compare_experiments failed: {e}")
        return False


# ─────────────────────────────────────────────────────────────────────
# 3. CROSS-EXPERIMENT FORCING-CONDITIONS TIMELINE
# ─────────────────────────────────────────────────────────────────────
def compare_forcing_conditions(experiments: List[Dict[str, Any]],
                               output_path: str) -> bool:
    """Timeline of forcing periods within the Qian window."""
    plt = _import_matplotlib()
    if plt is None or not experiments:
        return False

    try:
        n = len(experiments)
        fig, ax = plt.subplots(figsize=(12, max(3, 0.75 * n + 2)))

        # Light gray background for full Qian range
        ax.axvspan(QIAN_START_YEAR, QIAN_END_YEAR,
                   color='lightgray', alpha=0.25)

        # One horizontal bar per experiment
        for i, exp in enumerate(experiments):
            yr_start = exp.get('forcing_start')
            yr_end   = exp.get('forcing_end')
            period   = exp.get('forcing_period', 'baseline')
            color    = PERIOD_COLORS.get(period, 'gray')

            if yr_start is not None and yr_end is not None:
                duration = yr_end - yr_start + 1
                ax.barh(i, duration, left=yr_start,
                        height=0.6, color=color, alpha=0.85,
                        edgecolor='white', linewidth=2)
                ax.text((yr_start + yr_end + 1) / 2, i,
                        f'{yr_start}–{yr_end}',
                        ha='center', va='center',
                        color='white', fontweight='bold',
                        fontsize=10)

        ax.set_yticks(range(n))
        ax.set_yticklabels([
            e.get('case_name', f'exp_{i:03d}')
            for i, e in enumerate(experiments)
        ])
        ax.invert_yaxis()
        ax.set_xlim(QIAN_START_YEAR - 2, QIAN_END_YEAR + 2)
        ax.set_xlabel('Year')
        ax.set_title('Forcing Conditions — Qian DATM_CLMNCEP '
                     '(1948–2004)',
                     fontsize=14, fontweight='bold', pad=15)
        ax.grid(True, axis='x', alpha=0.3)

        # Year boundary labels
        ax.axvline(QIAN_START_YEAR, color='#555',
                   linestyle=':', linewidth=1, alpha=0.6)
        ax.axvline(QIAN_END_YEAR, color='#555',
                   linestyle=':', linewidth=1, alpha=0.6)

        # Period legend
        from matplotlib.patches import Patch
        handles = [
            Patch(color=PERIOD_COLORS[p],
                  label=p.capitalize(), alpha=0.85)
            for p in ('baseline', 'dry', 'wet')
        ]
        ax.legend(handles=handles, loc='upper right',
                  fontsize=10, framealpha=0.95)

        plt.tight_layout()
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        return True

    except Exception as e:
        logger.warning(f"compare_forcing_conditions failed: {e}")
        return False


# ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("ELM Setup Plotting — call via ELMExpManager._plot_setups()")
    print("  from core.elm_setup_plotting import (")
    print("      plot_domain_configuration,")
    print("      compare_experiments,")
    print("      compare_forcing_conditions,")
    print("  )")